// Copies Crew's Critter drawings (shared/faces.mjs in the Crew repo) into crew-faces.js, as a plain
// script the face window can load. Run it after the faces change in Crew:
//   node scripts/sync-faces.js [path/to/crew/shared/faces.mjs]
const fs = require('fs');
const path = require('path');

const from = process.argv[2] || path.join(__dirname, '..', '..', 'crew', 'shared', 'faces.mjs');
const source = fs.readFileSync(from, 'utf8').replace(/^export /gm, '');
const out = `// Generated by scripts/sync-faces.js from Crew's shared/faces.mjs: do not edit by hand.
// The Critters (Crew's agents' faces), drawn as SVG markup.
(function () {
${source}
  window.CrewFaces = { CRITTERS, SHAPES, DEFS, APP_ICON, prop, face, paint, mix, iconFor };
})();
`;
fs.writeFileSync(path.join(__dirname, '..', 'crew-faces.js'), out);
console.log('crew-faces.js written from', from);
